CC = gcc
CXX = g++

INCLUDES =
CFLAGS = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES)

.PHONY: all clean

all: clean inspect_pages map_pages

inspect_pages:

map_pages:

clean:
	rm -rf *.o inspect_pages map_pages
