#
# Makefile for Goldfish platform specific drivers
#
obj-$(CONFIG_GOLDFISH_PIPE)	+= goldfish_pipe_all.o
goldfish_pipe_all-objs := goldfish_pipe.o goldfish_pipe_v1.o goldfish_pipe_v2.o

obj-$(CONFIG_GOLDFISH_SYNC)	+= goldfish_sync.o
